MAX_AUDIO_UPLOAD_BYTES = 3 * 1024 * 1024
MAX_TRANSCRIPT_UPLOAD_BYTES = 30 * 1024

AUDIO_UPLOAD_TOO_LARGE_MESSAGE = "Upload audio file of size less than 3MB"
TRANSCRIPT_UPLOAD_TOO_LARGE_MESSAGE = "Upload transcript file of size less than 30KB"
